version: '3.9'

services:
  maccabisearch.api:
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    environment:
      - ConnectionStrings__MaccabiSearchDB="Host=maccabisearch.database;Post=5432;Database=maccabisearch;Username=postgres;Password=postgres;Include Error Detail=true"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001

  maccabisearch.database:
    volumes:
      - ./.development/maccabisearch-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maccabisearch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  maccabisearch.pgadmin:
    ports:
      - "8888:80"
    volumes:
      - ./.development/maccabisearch-pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=unused
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SUPPORT_SSH_TUNNEL=False
