version: '3.9'

services:
  maccabisearch.api:
    image: ${DOCKER_REGISTRY-}maccabisearchapi
    container_name: maccabisearch.api
    build:
      context: .
      dockerfile: MaccabiSearch.Api/Dockerfile
    depends_on:
      - maccabisearch.database
    networks:
      - db-network
      - api-network

  maccabisearch.database:
    image: postgres:13.8-bullseye
    container_name: maccabisearch.database
    networks:
      - db-network

  maccabisearch.pgadmin:
    links:
      - maccabisearch.database:maccabisearch.database
    container_name: maccabisearch.pgadmin
    image: dpage/pgadmin4
    depends_on:
      - maccabisearch.database
    networks:
      - db-network

  maccabisearch.redis:
    image: redis:latest
    networks:
      - api-network

networks:
    api-network:
    db-network:
      driver: bridge
