// <auto-generated />
using System;
using MaccabiSearch.Domain.Services.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaccabiSearch.Domain.Services.Implementations.EntityFramework.Migrations
{
    [DbContext(typeof(MaccabiSearchDbContext))]
    [Migration("20240311182244_CreateTableSearchResults")]
    partial class CreateTableSearchResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaccabiSearch.Domain.Models.PostgresEntities.SearchResultPgEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("EnteredDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SearchEngine")
                        .HasColumnType("integer")
                        .HasColumnName("search_engine");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("search_results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
